# -*- coding: utf-8 -*-
"""wONE.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1jRpvhpa2sSRde05e0UU-5-GeujY5Y2AN
"""

import pandas as pd
import numpy as np

from sklearn.model_selection import train_test_split
from sklearn.metrics import accuracy_score, f1_score, roc_auc_score, confusion_matrix

from sklearn.pipeline import Pipeline
from sklearn.preprocessing import StandardScaler
from sklearn.linear_model import LogisticRegression
from sklearn.svm import SVC
from sklearn.neighbors import KNeighborsClassifier
from sklearn.naive_bayes import GaussianNB

from sklearn.ensemble import (
    RandomForestClassifier,
    ExtraTreesClassifier,
    GradientBoostingClassifier,
    HistGradientBoostingClassifier
)

import matplotlib.pyplot as plt


# ====== 1) Загрузка данных ======
villageregion = pd.read_excel("/content/villageregion.xlsx")
migvill = pd.read_excel("/content/migvill.xlsx")

villageregion = villageregion.rename(columns={"Unnamed: 0": "Регион"})
migvill = migvill.rename(columns={"Unnamed: 0": "Регион"})

# ====== 2) Ищем столбец миграционного прироста ======
target_col = None
for c in migvill.columns:
    lc = str(c).lower()
    if "миграцион" in lc and "прирост" in lc:
        target_col = c
        break
if target_col is None:
    raise ValueError(f"Не нашёл столбец с миграционным приростом. Колонки: {list(migvill.columns)}")

# ====== 3) Merge ======
df = villageregion.merge(migvill[["Регион", target_col]], on="Регион", how="inner").copy()
df = df.rename(columns={target_col: "Миграционный прирост"})
print("После merge размер:", df.shape)

# ====== 4) Класс ======
df["Класс_миграции"] = (df["Миграционный прирост"] > 0).astype(int)

# ====== 5) X/y ======
X = df.drop(columns=["Регион", "Миграционный прирост", "Класс_миграции"])
y = df["Класс_миграции"]

X = X.select_dtypes(include=["number"]).copy()
X = X.replace([np.inf, -np.inf], np.nan)
X = X.fillna(X.median(numeric_only=True))

print("X shape:", X.shape, "| y distribution:\n", y.value_counts())

# ====== 6) Train/test split ======
if y.nunique() == 2 and y.value_counts().min() >= 2:
    X_train, X_test, y_train, y_test = train_test_split(
        X, y, test_size=0.25, random_state=42, stratify=y
    )
else:
    X_train, X_test, y_train, y_test = train_test_split(
        X, y, test_size=0.25, random_state=42
    )

# ====== Вспомогательные функции ======
def _sigmoid(z):
    return 1 / (1 + np.exp(-z))

def get_proba_1(model, X):
    """
    Возвращает вероятность класса 1:
    - если есть predict_proba -> берём её
    - иначе decision_function -> прогоняем через sigmoid (для AUC)
    """
    if hasattr(model, "predict_proba"):
        return model.predict_proba(X)[:, 1]
    if hasattr(model, "decision_function"):
        scores = model.decision_function(X)
        return _sigmoid(scores)
    return None

def evaluate(name, model, X_train, y_train, X_test, y_test):
    model.fit(X_train, y_train)
    pred = model.predict(X_test)

    proba = get_proba_1(model, X_test)
    acc = accuracy_score(y_test, pred)
    f1 = f1_score(y_test, pred)

    auc = np.nan
    if proba is not None and len(np.unique(y_test)) == 2:
        auc = roc_auc_score(y_test, proba)

    cm = confusion_matrix(y_test, pred)

    return {
        "Model": name,
        "Accuracy": acc,
        "F1": f1,
        "ROC_AUC": auc,
        "TN": cm[0, 0],
        "FP": cm[0, 1],
        "FN": cm[1, 0],
        "TP": cm[1, 1],
        "ConfusionMatrix": cm
    }

import matplotlib.pyplot as plt

import matplotlib.pyplot as plt

def plot_confusion_matrix(cm, title="Confusion matrix"):
    plt.figure(figsize=(4, 4))
    # cmap="binary" — чёрно-белая палитра с контрастными оттенками
    plt.imshow(cm, cmap="binary", interpolation='nearest')
    plt.title(title)
    plt.xlabel("Predicted")
    plt.ylabel("True")
    plt.xticks([0, 1], ["0", "1"])
    plt.yticks([0, 1], ["0", "1"])

    # Подписи в ячейках
    for i in range(cm.shape[0]):
        for j in range(cm.shape[1]):
            color = "black" if cm[i, j] > cm.max()/2 else "white"
            plt.text(j, i, str(cm[i, j]), ha="center", va="center", color=color)

    plt.tight_layout()
    plt.show()



# ====== 10 моделей/настроек (эксперимент) ======
models = {
    # 1) RF (как у тебя, 800 деревьев)
    "RF_800_balanced_leaf2": RandomForestClassifier(
        n_estimators=800, random_state=42, class_weight="balanced_subsample",
        min_samples_leaf=2, n_jobs=-1
    ),

    # 2) RF (2000 деревьев — проверяем замечание препода)
    "RF_2000_balanced_leaf2": RandomForestClassifier(
        n_estimators=2000, random_state=42, class_weight="balanced_subsample",
        min_samples_leaf=2, n_jobs=-1
    ),

    # 3) RF с ограничением глубины (вариант настройки дерева)
    "RF_800_depth6": RandomForestClassifier(
        n_estimators=800, random_state=42, class_weight="balanced_subsample",
        max_depth=6, min_samples_leaf=2, n_jobs=-1
    ),

    # 4) ExtraTrees
    "ExtraTrees_800": ExtraTreesClassifier(
        n_estimators=800, random_state=42, class_weight="balanced",
        min_samples_leaf=2, n_jobs=-1
    ),

    # 5) GradientBoosting (классический)
    "GradientBoosting": GradientBoostingClassifier(random_state=42),

    # 6) HistGradientBoosting (быстрее, часто сильный)
    "HistGradientBoosting": HistGradientBoostingClassifier(random_state=42),

    # 7) Логистическая регрессия (со стандартизацией)
    "LogReg_L2": Pipeline([
        ("scaler", StandardScaler()),
        ("clf", LogisticRegression(max_iter=5000, class_weight="balanced", random_state=42))
    ]),

    # 8) SVM RBF (с вероятностями -> AUC можно считать)
    "SVC_RBF": Pipeline([
        ("scaler", StandardScaler()),
        ("clf", SVC(kernel="rbf", probability=True, class_weight="balanced", random_state=42))
    ]),

    # 9) KNN (baseline)
    "KNN_k7": Pipeline([
        ("scaler", StandardScaler()),
        ("clf", KNeighborsClassifier(n_neighbors=7))
    ]),

    # 10) Naive Bayes (baseline)
    "GaussianNB": GaussianNB(),
}

results = []
cms = {}

for name, model in models.items():
    r = evaluate(name, model, X_train, y_train, X_test, y_test)
    results.append({k: v for k, v in r.items() if k != "ConfusionMatrix"})
    cms[name] = r["ConfusionMatrix"]

results_df = pd.DataFrame(results)
results_df = results_df.sort_values(by=["ROC_AUC", "F1", "Accuracy"], ascending=False)

print("\n=== Таблица результатов (топ) ===")
print(results_df[["Model", "Accuracy", "F1", "ROC_AUC", "TN", "FP", "FN", "TP"]].head(10))

best_model_name = results_df.iloc[0]["Model"]
best_cm = cms[best_model_name]

print("\nЛучшая модель по сортировке:", best_model_name)
print("Confusion matrix:\n", best_cm)

# Визуально матрица ошибок (как просит препод)
plot_confusion_matrix(best_cm, title=f"Confusion matrix — {best_model_name}")

# ====== Сохраняем эксперимент в Excel ======
out_path = "/content/experiment_models_results.xlsx"
with pd.ExcelWriter(out_path, engine="openpyxl") as writer:
    results_df.to_excel(writer, index=False, sheet_name="results")
    # отдельный лист с confusion matrix лучшей модели
    pd.DataFrame(best_cm, index=["True_0", "True_1"], columns=["Pred_0", "Pred_1"]) \
      .to_excel(writer, sheet_name="best_confusion_matrix")

print("\n✅ Сохранено:", out_path)